#!/bin/bash
reset;
sudo cmake ..; 
sudo make; 
echo -- Program Built;
echo -- ChainFind;
sudo ./test-ChainFind | tee ChainTestFind.csv;
echo -- Chain Insert;
sudo ./test-ChainInsert | tee ChainTestInsert.csv;
echo -- Open Find;
sudo ./test-OpenFind | tee OpenTestFind.csv;
echo -- Open Insert;
sudo ./test-OpenInsert | tee OpenTestInsert.csv;
echo -- Moving;
cp ChainTestFind.csv ..;
cp  ChainTestInsert.csv ..;
cp  OpenTestFind.csv ..;
cp OpenTestInsert.csv ..;
(cd ..; git add *;)
echo -- Added to Git, please Commit and Push;
